{{- $fsArchives := eq .Values.archiveStorage.type "fs" -}}
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ include "clp-presto.componentFullname" (dict "root" . "component" "worker") }}
  labels:
    {{- include "clp-presto.labels" . | nindent 4 }}
    app.kubernetes.io/component: "worker"
spec:
  replicas: {{ .Values.worker.replicas | int }}
  selector:
    matchLabels:
      {{- include "clp-presto.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "worker"
  template:
    metadata:
      annotations:
        {{- include "clp-presto.configChecksumAnnotation" . | nindent 8 }}
      labels:
        {{- include "clp-presto.labels" . | nindent 8 }}
        app.kubernetes.io/component: "worker"
    spec:
      {{- with .Values.serviceAccountName }}
      serviceAccountName: {{ . | quote }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      {{- include "clp-presto.schedulingConfigs" .Values.worker | nindent 6 }}
      initContainers:
        {{- with .Values.worker.extraInitContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "clp-presto.installPluginInitContainer" (dict
            "root" . "component" "worker"
          ) | nindent 8 }}
        - name: "setup-configs"
          {{- include "clp-presto.imageSpec" (dict "root" . "component" "kubectl") | nindent 10 }}
          command: ["/bin/sh", "/scripts/worker-setup-configs.sh"]
          {{- include "clp-presto.resources" .Values.worker.setupConfigs.resources | nindent 10 }}
          volumeMounts:
            - name: "presto-config"
              mountPath: "/etc/presto-config"
              readOnly: true
            - name: "presto-etc"
              mountPath: "/opt/presto-server/etc"
            - name: "presto-scripts"
              mountPath: "/scripts"
              readOnly: true
      containers:
        - name: "worker"
          {{- include "clp-presto.imageSpec" (dict "root" . "component" "worker") | nindent 10 }}
          {{- include "clp-presto.resources" .Values.worker.resources | nindent 10 }}
          ports:
            - name: "presto-worker"
              containerPort: 8889
          volumeMounts:
            - name: "presto-catalog"
              mountPath: "/opt/presto-server/etc/catalog"
              readOnly: true
            - name: "presto-config"
              mountPath: "/opt/presto-server/etc/velox.properties"
              subPath: "worker-config-velox.properties"
              readOnly: true
            - name: "presto-etc"
              mountPath: "/opt/presto-server/etc"
            - name: "presto-plugin"
              mountPath: "/opt/presto-server/plugin/clp"
              readOnly: true
            {{- if $fsArchives }}
            - name: "archives"
              mountPath: {{ .Values.archiveStorage.fs.mountPath | quote }}
              readOnly: true
            {{- end }}
          readinessProbe:
            {{- toYaml .Values.probes.readiness | nindent 12 }}
            tcpSocket: &worker-health-check
              port: "presto-worker"
          livenessProbe:
            {{- toYaml .Values.probes.liveness | nindent 12 }}
            tcpSocket: *worker-health-check
      volumes:
        {{- include "clp-presto.commonVolumes" (dict
            "root" . "component" "worker"
          ) | nindent 8 }}
        - name: "presto-etc"
          emptyDir: {}
        - name: "presto-scripts"
          configMap:
            name: {{ include "clp-presto.componentFullname" (dict "root" . "component" "config") }}
            items:
              - key: "worker-setup-configs.sh"
                path: "worker-setup-configs.sh"
            defaultMode: 0755
        {{- if $fsArchives }}
        {{- include "clp-presto.archivesVolume" (dict
            "root" .
            "requiredBy" "archiveStorage.type is \"fs\""
          ) | nindent 8 }}
        {{- end }}
